services:
  nova-domus:
    container_name: nova-domus
    build: .
    volumes:
      - ./data:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Asia/Shanghai
      HASS_URL: http://XXXXXX
    restart: always
