services:
  nova-domus:
    container_name: nova-domus
    image: ghcr.io/amedello/nova-domus
    volumes:
      - /path/to/ha-fusion:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Stockholm
      HASS_URL: http://192.168.1.241:8123
    restart: always

  moviepilot:
    container_name: moviepilot
    image: jxxghp/moviepilot:latest
    network_mode: bridge
    ports:
      - "3000:3000"
    volumes:
      - /path/to/moviepilot/data:/config
      - /path/to/media:/media
    environment:
      TZ: Asia/Shanghai
      SUPERUSER: admin
      API_TOKEN: moviepilot
    restart: always
